-- You don't need to set any of these options.
-- IMPORTANT!: this is only a showcase of how you can set default options!
--

-- require("telescope").setup {
--   extensions = {
--     file_browser = {
--       theme = "ivy",
--       -- disables netrw and use telescope-file-browser in its place
--       hijack_netrw = true,
--       mappings = {
--         ["i"] = {
--           -- your custom insert mode mappings
--         },
--         ["n"] = {
--           -- your custom normal mode mappings
--         },
--       },
--     },
--   },
-- }
-- -- To get telescope-file-browser loaded and working with telescope,
-- -- you need to call load_extension, somewhere after setup function:
-- require("telescope").load_extension "file_browser"

-- vim.api.nvim_set_keymap(
--   "n",
--   "<space>fb",
--   ":Telescope file_browser",
--   { noremap = true }
-- )

-- Example of how to confiugre it
-- local fb_actions = require "telescope".extensions.file_browser.actions
-- -- mappings in file_browser extension of telescope.setup
-- ...
--       mappings = {
--         ["i"] = {
--           -- remap to going to home directory
--           ["<C-h>"] = fb_actions.goto_home_dir
--           ["<C-x>"] = function(prompt_bufnr)
--             -- your custom function
--           end
--         },
--         ["n"] = {
--           -- unmap toggling `fb_actions.toggle_browser`
--           f = false,
--         },
-- ...
